-- inserts documento.tipo_documento
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Foto inscripción','Foto inscripción','FI', true,1,5,'png,jpg','/default-domain/workspaces/Pruebas Planestic/Inscripcion/Fotos','Picture');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Documentos','Documento identificación','DI', true,2,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/Documentos','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Formación académica','Formación académica','FA', true,3,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/FormacionAcademica','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Experiencia laboral','Experiencia laboral','EL', true,4,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/ExperienciaLaboral','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Propuesta grado','Propuesta grado','PG', true,5,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/PropuestaGrado','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Documento soporte','Documento soporte','DS', true,6,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/DocumentosSoporte','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Descuentos matrícula','Descuentos matrícula','DM', true,7,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/Descuentos','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Comprobante pago','Comprobante pago','CPO', true,8,5,'pdf','/default-domain/workspaces/Pruebas Planestic/Inscripcion/ComprobantePago','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Resolución registro calificado','Documento de resolución asociada a un registro calificado','RRC', true,9,5,'pdf','/desarrollo/workspaces/sga/Proyectos/Soportes','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Acto adminnistrativo proyecto','Documento de acto administrativo por el que se crea un proyecto academico','AAP', true,10,5,'pdf','/desarrollo/workspaces/sga/Proyectos/Soportes','File');
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Resolución asignación coordinador','Documento de acto administrativo por el que se asigna un nuevo coordinador a un proyecto','RAC', true,11,5,'pdf','/desarrollo/workspaces/sga/Proyectos/Coordinacion','File');
